[project]
name = "langchain-crash-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "VenkateshVandana", email = "venkivandana14@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
langchain-crash-course = "langchain_crash_course:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
